In [4]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")
dfMolise = df.loc[df['denominazione_regione'] == "Molise"]
dfSardegna = df.loc[df['denominazione_regione'] == "Sardegna"]

In [5]:
dfMolise.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
10,2020-02-24T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2020-02-25T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,2020-02-26T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,2020-02-27T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2020-02-28T18:00:00,ITA,14,Molise,41.557748,14.659161,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dfSardegna.head()

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
15,2020-02-24T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2020-02-25T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2020-02-26T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2020-02-27T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2020-02-28T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dfSardegna = dfSardegna.drop(columns=['note', 'note_test', 'note_casi'])

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,totale_casi,tamponi,casi_testati,ingressi_terapia_intensiva,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
15,2020-02-24T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2020-02-25T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2020-02-26T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2020-02-27T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2020-02-28T18:00:00,ITA,20,Sardegna,39.215312,9.110616,0,0,0,0,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7785,2021-02-28T17:00:00,ITA,20,Sardegna,39.215312,9.110616,215,19,234,12621,...,41191,761789,531953.0,0.0,41175.0,16.0,635090.0,126699.0,ITG,ITG2
7806,2021-03-01T17:00:00,ITA,20,Sardegna,39.215312,9.110616,210,19,229,12576,...,41236,768303,533202.0,1.0,41220.0,16.0,636589.0,131714.0,ITG,ITG2
7827,2021-03-02T17:00:00,ITA,20,Sardegna,39.215312,9.110616,206,20,226,12513,...,41306,778916,535261.0,1.0,41290.0,16.0,639051.0,139865.0,ITG,ITG2
7848,2021-03-03T17:00:00,ITA,20,Sardegna,39.215312,9.110616,192,20,212,12494,...,41407,783633,537630.0,1.0,41391.0,16.0,641892.0,141741.0,ITG,ITG2
7869,2021-03-04T17:00:00,ITA,20,Sardegna,39.215312,9.110616,193,23,216,12485,...,41488,786233,539386.0,3.0,41472.0,16.0,644004.0,142229.0,ITG,ITG2

In [12]:
dfMolise.to_csv('dpc-covid19-ita-molise.csv', index=False)
dfSardegna.to_csv('dpc-covid19-ita-sardegna.csv', index=False)